-- La columna id de missing_ingredients quedó sin valor por defecto (probablemente
-- se perdió al migrar de proyecto de Supabase), por lo que cualquier INSERT sin
-- id explícito fallaba con "null value in column id violates not-null constraint".
-- Esto bloqueaba agregar materias primas faltantes a productos para TODOS los
-- roles de usuario, no solo para roles sin permiso.
ALTER TABLE missing_ingredients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Sincronizar el contador de la nueva identity para que arranque después del
-- id más alto ya existente y no choque con filas cargadas anteriormente.
SELECT setval(
  pg_get_serial_sequence('missing_ingredients', 'id'),
  COALESCE((SELECT MAX(id) FROM missing_ingredients), 0) + 1,
  false
);
